# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-06-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=140, verbose_name='密码')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='邮箱')),
                ('info', models.CharField(default='Martin is NB', max_length=20, verbose_name='简介')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('confirm', models.BooleanField(default=False, verbose_name='激活状态')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
