# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-06-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=20)),
                ('article', tinymce.models.HTMLField()),
            ],
        ),
    ]
